export const style = {
    navbar: 'navbar is-transparent',
    navbarBurger: 'navbar-burger',
    navbarBrand: 'navbar-brand',
    navbarItem: 'navbar-item',
    navbarEnd: 'navbar-end',
    fieldIsGrouped: 'field is-grouped',
    btnInfoLight: 'button is-info is-light',
    btnInfo: 'button is-info',
    btnWarningLight: 'button is-warning is-light',
    btnPrimaryLight: 'button is-primary is-light',
    btnCloseLight: 'button is-danger is-light is-left',
    loginForm: 'formLogin card',
    inputDefault: 'input is-hovered',
}
